### ISSUE TITLE
Remove Chrome Store link and add local setup instructions

### ISSUE THREAD

**Issue by dnapier** [prabhakar267/github-email-extractor#5]
The URL returns a 404.

**Comment by prabhakar267** [comment]
It was taken down by Google Chrome Store team.
The Chrome store link needs to be removed and instructions for developers to enable it needs to be added.

**Comment by vladimyr** [comment]
> It was taken down by Google Chrome Store team.

Due to violation of some weird policy? :thinking:

**Comment by prabhakar267** [comment]
@vladimyr Yes!

**Comment by vladimyr** [comment]
Which one in particular? This is classic example of _userscript_ and can not imagine scripts suddenly become outlawed. Is usage of 3rd party resolver service problematic bit here?

**Comment by anthony-roger** [comment]
Hello,

As a workaround: 

1. Go to https://github.com/prabhakar267/github-email-extractor and click on `clone or download` green button
2. Clone the project on your computer. (Unzip if you are not using Git).
3. Go to `chrome://extensions/` 
    - Tick `Developer mode` button
    - Click on `Load unpacked extension`
    - Select `src` folder containing the `manifest` file
4. Enjoy your extension.

Best regards.
